export const locationMapUrl = 'https://goo.gl/maps/5nEPuX6TQAHhju2q9'
export const locationName = 'Himachal Bhawan'
export const email = 'example@example.com'
export const phone = '+91-988888888'
export const clubNameShort = 'dtm'
export const whatsAppLink = '#'
export const instagramLink = '#'
export const youtubeLink = '#'
